platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfmobile/ginkgo
inputs:
- name: pull-request
  path: gopath/src/github.com/EngineerBetter/cdgo-cli
run:
  path: gopath/src/github.com/EngineerBetter/cdgo-cli/ci/scripts/test