---
jobs:
- name: test
  public: true
  plan:
  - get: cdgo-cli
    trigger: true
  - task: test
    file: cdgo-cli/ci/tasks/test.yml
- name: github
  public: true
  plan:
  - get: cdgo-cli
    trigger: false
    passed: [test]
  - task: build
    file: cdgo-cli/ci/tasks/build.yml
  - put: cdgo-cli-release
    params:
      name: cdgo-cli/version
      tag: cdgo-cli/version
      tag_prefix: v
      globs: [build/cdgo-cli*]
- name: test-prs
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: pull-request
    params:
      path: pull-request
      status: pending
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cfmobile/ginkgo
      inputs:
      - name: pull-request
        path: gopath/src/github.com/EngineerBetter/cdgo-cli
      run:
        path: gopath/src/github.com/EngineerBetter/cdgo-cli/ci/scripts/test
    on_failure:
      put: pull-request
      params:
        path: pull-request
        status: failure
  - put: pull-request
    params:
      path: pull-request
      status: success

resources:
- name: cdgo-cli
  type: git
  source:
    uri: https://github.com/EngineerBetter/cdgo-cli.git
    branch: master
- name: pull-request
  type: pull-request
  source:
    access_token: ((github_access_token))
    repo: EngineerBetter/cdgo-cli
- name: cdgo-cli-release
  type: github-release
  source:
    user: EngineerBetter
    repository: cdgo-cli
    access_token: ((github_access_token))


resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr