---
jobs:
- name: test
  public: true
  plan:
  - get: cdgo-cli
    trigger: true
  - task: test
    file: cdgo-cli/ci/tasks/test.yml
- name: github
  public: true
  plan:
  - get: cdgo-cli
    trigger: true
    passed: [test]
  - task: build
    file: cdgo-cli/ci/tasks/build.yml
  - put: cdgo-cli-release
    params:
      name: cdgo-cli/version
      tag: cdgo-cli/version
      tag_prefix: v
      globs: [build/cdgo-cli*]

resources:
- name: cdgo-cli
  type: git
  source:
    uri: https://github.com/EngineerBetter/cdgo-cli.git
    branch: master
- name: cdgo-cli-release
  type: github-release
  source:
    user: EngineerBetter
    repository: cdgo-cli
    access_token: {{github-access-token}}